# Generated by Django 5.1.4 on 2025-07-06 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0004_rename_can_assign_roles_rol_can_access_historical_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha',
            new_name='fecha_mantenimiento',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tecnico_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(default='Desonocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='IS.dispositivoiot'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='duracion_horas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
