# Generated by Django 5.1.4 on 2025-07-06 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0005_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocoloemergencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre': 'Supervisor de Planta'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
