# Generated by Django 5.1.4 on 2025-07-06 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0006_alter_protocoloemergencia_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoiot',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivoiot',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
